### ISSUE TITLE
Fork for Switch?

### ISSUE THREAD

**Issue by MarvinXLII** [mastermind1919/OctopathBossRandomizer#2]
Hey, I've cloned this repo and have managed to make it compatible with the Switch release. Do you mind if I make an official fork of this and post releases there? They wouldn't be compatible for everything, so I wouldn't plan on submitting any pull requests.

I saw no license deeming this as open source, so I figured I should double check with you. No worries if you're against it. It was a fun little project regardless.

**Comment by mastermind1919** [comment]
A fork of this is completely fine by me. I need to figure out the whole licensing thing, but this project is completely open to modification.

**Comment by MarvinXLII** [comment]
Great, thanks!
